name: Run tests
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'

jobs:
  list-changed-files:
    name: Prepare list of changed files
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.files.outputs.all }}
      changed-count: ${{ steps.count.outputs.changed-count }}
    steps:
      - name: Get a list of changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Count changed `*.go` files
        id: count
        run: |
          echo "::set-output name=changed-count::$(echo \"${{ steps.files.outputs.all }}\" |
          xargs -n 1 |
          grep -c '\.go$')"
      - name: Print step outputs
        run: |
          echo ${{ steps.files.outputs.all }}
          echo ${{ steps.count.outputs.changed-count }}

  run-go-test:
    name: Run tests on changed files
    runs-on: ubuntu-latest
    needs: list-changed-files
    if: needs.list-changed-files.outputs.changed-count > 0
    steps:
      - name: Get changed `*.go` files list
        id: dirs
        run: |
          echo "::set-output name=changed-dirs::$(echo ${{ needs.list-changed-files.outputs.changed-files }} |
          xargs -n 1 |
          grep '\.go$' |
          sort -u |
          rev | cut -d '/' -f 2- | rev |
          sed 's:.*:./&:' |
          tr '\n' ' ' | sed 's/\s$/\n/')"
      - name: Print step outputs
        run: |
          echo ${{ steps.dirs.outputs.changed-dirs }}
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup work node
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run tests
        id: run-go-tests
        run: |
          echo "::set-output name=passed::$(go mod tidy
          go test ${{ steps.dirs.outputs.changed-dirs }} |
          grep '^ok' | cut -d '\t' -f 2 |
          tr '\n' ' ' | sed 's/\s$/\n/')"
      - name: Print passed tests
        run: |
          echo "${{ steps.run-go-tests.passed }} |
          tr ' ' '\n'"
