name: run-go-test
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
jobs:
  list-changed-files:
    name: Prepare list of changed files
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed.outputs.changed-files}}
      changed-count: ${{ steps.count.outputs.changed-count}}
    steps:
      - name: Get a list of changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Generate a list of changed files
        id: changed
        run: |
          echo "::set-output name=changed-files::$(echo \"${{ steps.files.outputs.all }}\")"
      - name: Generate a count of changed `*.go` files
        id: count
        run: |
          echo "::set-output name=changed-count::$(echo \"${{ steps.files.outputs.all }}\" |
          xargs -n 1 |
          grep -c '\.go$')"
      - name: Print step outputs
        run: |
          echo ${{ steps.changed.outputs.changed-files }}
          echo ${{ steps.count.outputs.changed-count }}
          
  run-go-test:
    name: Run tests on changed files
    runs-on: ubuntu-latest
    needs: list-changed-files
    if: needs.list-changed-files.outputs.changed-count > 0
    steps:
      - name: Get changed `*.go` files list
        run: |
          echo "changed-dirs=$(echo \"${{ needs.list-changed-files.outputs.changed-files }}\" |
          xargs -n 1 |
          grep '\.go$' |
          sort -u |
          dirname)" >> $GITHUB_ENV
          echo ${env.changed-dirs[@]}
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup work node
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run tests
        run: |
          go mod tidy
          go test ${env.changed-dirs[@]}