name: run-go-test
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed.outputs.changed}}
      changed-count: ${{ steps.count.outputs.count}}
    steps:
      - name: Get a list of changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Generate a list of changed files
        id: changed
        run: |
          echo "::set-output name=changed::$(echo \"${{ steps.files.outputs.all }}\"
      - name: Generate a count of changed `*.go` files
        id: count
        run: |
          echo "::set-output name=count::$(echo \"${{ env.CHANGED }}\" |
          xargs -n 1 |
          grep -c \".*\")"
      - name: Print step outputs
        run: |
          echo ${{ steps.*.outputs.* }}
          
  run-go-test:
    runs-on: ubuntu-latest
    needs: list-changed-files
    if: ${{ needs.list-changed-files.outputs.changed-count }} > 0
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup work node
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run tests
        run: |
          go mod tidy
          go test ./...