name: run-go-test
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
jobs:
  run-go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go mod tidy
      - run: go test ./...
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: echo "files=(\"${{ steps.files.outputs.all }}\")" >> $GITHUB_ENV
      - id: loop
        run: |
          for f in ${files[@]}; do
            echo "${f}"
          done
      - id: grep
        run: |
          echo ${files[@]} | grep '\.go$'