name: run-go-test
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get a list of changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: List and count changed `*.go` files
        run: |
          CHANGED=$(echo "${{ steps.files.outputs.all }}" |
          xargs -n 1 |
          grep -c ".*")
          echo $CHANGED
          
  run-go-test:
    runs-on: ubuntu-latest
    needs: list-changed-files
    # if: env.CHANGED > 0
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup work node
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run tests
        run: |
          go mod tidy
          go test ./...