name: run-go-test
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
jobs:
  run-go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: dirs
        run: |
          printf -- '%s\n' "${{ steps.files.outputs.all }}"
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go mod tidy
      - run: go test ./...