name: run-go-test
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: for file in ${{ steps.files.outputs.all }}; do; echo $file; done
  run-go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go mod tidy
      - id: test
        run: go test ./...