name: run-go-test
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
jobs:
  run-go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Get a list of changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Check for any changed `*.go` files
        run: |
          echo "${{ steps.files.outputs.all }}" |
          xargs -n 1 |
          grep "\.go$"
      - name: Setup work node
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run tests
        run: |
          go mod tidy
          go test ./...