name: Update tasks data
on:
  push:
    paths:
      - '**.md'
      - '.github/workflows/update_tasks.yml'
      - '.github/actions/update_tasks/**'

jobs:
  get-task-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Get task data
      run: |
        apt-get update && \
        apt-get install -y --no-install-recommends \
        pandoc
        pip install --upgrade pip && \
        pip install -r requirements.txt
        python tasks.py
    - name: Commit README.md
      run: |
        git config --local core.autocrlf false
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add README.md && git add --renormalize README.md
        git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
        git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
        NO_PAGER=1 git --no-pager diff HEAD^
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
